using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The class that helps display maps generated by MapGenerator
/// </summary>
public class mapDisplayer : MonoBehaviour {

    public Renderer noisePlane;

    /// <summary>
    /// Generates a simple black and white colormap from the raw map, then renders it
    /// </summary>
    public void RenderRawMap(float[,] noiseMap)
    {
        int width = noiseMap.GetLength(0);
        int height = noiseMap.GetLength(1);
        Texture2D texture = new Texture2D(width, height);

        Color[] colorMap = new Color[height * width];

        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
                colorMap[y * width + x] = Color.Lerp(Color.black, Color.white, noiseMap[x, y]); //Black = 0, white = 1

        texture.SetPixels(colorMap);
        texture.Apply();

        //We're using sharedMaterial instead of material because material is only usuable in run-time
        //But it would be nice to be able to see this rendering in the editor too
        noisePlane.sharedMaterial.mainTexture = texture;
        noisePlane.transform.localScale = new Vector3(width, 1, height); //Stretching to match map dimensions
    }


    /// <summary>
    /// Renders the colormap directly
    /// </summary>
    public void RenderColorMap(float[,] noiseMap, TerrainLayer[] layers)
    {

        int width = noiseMap.GetLength(0);
        int height = noiseMap.GetLength(1);

        Color[] colorMap = new Color[height * width];

        //Going through the colormap array and assigning colors based off the selected biome
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
            {
                float value = noiseMap[x, y];
                foreach (TerrainLayer layer in layers)
                {
                    if (value <= layer.heightUpperBound)
                    {
                        colorMap[width * y + x] = layer.color;
                        break;
                    }
                }
            }

        Texture2D texture = new Texture2D(width, height);

        texture.SetPixels(colorMap);
        texture.filterMode = FilterMode.Point;
        texture.wrapMode = TextureWrapMode.Clamp; //Prevents The texture edges from wrapping and showing the color from another side of the texture
        texture.Apply();

        //We're using sharedMaterial instead of material because material is only usuable in run-time
        //But it would be nice to be able to see this rendering in the editor too
        noisePlane.sharedMaterial.mainTexture = texture;
        noisePlane.transform.localScale = new Vector3(width, 1, height); //Stretching to match map dimensions
    }
}
