using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The class that helps display maps generated by MapGenerator
/// </summary>
public class mapDisplayer : MonoBehaviour {

    public Renderer texturePane;
    public MeshFilter meshFilter;
    public MeshRenderer meshRenderer;


    public void DrawTexture(Texture texture)
    {
        //We're using sharedMaterial instead of material because material is only usuable in run-time
        //But it would be nice to be able to see this rendering in the editor too
        texturePane.sharedMaterial.mainTexture = texture;
        texturePane.transform.localScale = new Vector3(texture.width/10, 1, texture.height/10); //Stretching to match map dimensions
    }


    public void DrawMesh(MeshData meshData, Texture texture)
    {
        meshFilter.sharedMesh = meshData.produceMesh();
        meshRenderer.sharedMaterial.mainTexture = texture;
    }
}
